
# tap repositories and their packages

## cask
tap caskroom/cask
brew brew-cask
cask electrum
cask git
cask intellij-idea
cask iterm2
cask java
cask karabiner
cask kobito
cask vagrant
cask virtualbox
cask vlc

## rcmdnk/file
tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew git
brew tig
brew maven
